### ISSUE TITLE
现在这个项目还维护吗？

### ISSUE THREAD

**Issue by colinwdk** [fagongzi/gateway#1]

**Comment by colinwdk** [comment]
github.com/fagongzi/net 找不到

**Comment by zhangxu19830126** [comment]
github.com/fagongzi/net 被我删除了，这个库被我重构了。新的地址是github.com/fagongzi/goetty，近期会修复这个问题

**Comment by colinwdk** [comment]
好的，谢谢

**Comment by zhangxu19830126** [comment]
已经更新了.但是readme里面的二进制包是老的
