### ISSUE TITLE
能举个例子 API 聚合的使用方法吗

### ISSUE THREAD

**Issue by hlj2722** [fagongzi/gateway#10]

**Comment by zhangxu19830126** [comment]
你可以看下在线demo的API配置里面的“用户聚合信息”设置，这个API就是聚合的例子

**Comment by zhangxu19830126** [comment]
http://demo-admin.fagongzi.win/#/apis   用户名和密码：admin/admin

**Comment by hlj2722** [comment]
这个例子看过了，只是不知道完整的请求的URL地址是什么，不知道在demo中如何发送聚合的API

**Comment by zhangxu19830126** [comment]
完整的外部访问URL是：http://demo-proxy.fagongzi.win/api/users/1

**Comment by zhangxu19830126** [comment]
http://demo-proxy.fagongzi.win/api/users/1/account和http://demo-proxy.fagongzi.win/api/users/1/base这个2个信息的聚合。

**Comment by hlj2722** [comment]
谢谢 @zhangxu19830126 在你的demo中测试可以使用 ，不过我在我本机测试时不能通过，测试时启动两个进程
./admin --addr=:8080  --etcd-addr=http://127.0.0.1:2379 -etcd-prefix=dev
./proxy --cpus=1 --config ./config.json --log-file ./proxy.log --log-level=info
开启了三个端口 80 8080 8081
而后使用 http://127.0.0.1:8081/api/users/1 请求数据  出现错误503

**Comment by zhangxu19830126** [comment]
你的backend server启动了么？

**Comment by zhangxu19830126** [comment]
503是后台Server应该没有启动或者有问题吧

**Comment by zhangxu19830126** [comment]
gateway只是个请求转发，并不处理真实业务，所以真实的请求处理需要一个后端服务的

**Comment by zhangxu19830126** [comment]
我的在线demo，是启动了一个backend server 处理http请求的

**Comment by hlj2722** [comment]
编译 backend 后 启动
./backend --addr 127.0.0.1:8888
base 和 account API可以通过127.0.0.1:8888/api/users/1/base, 127.0.0.1:8888/api/users/1/account 访问，但是聚合API 127.0.0.1:8888/api/users/1 就不能访问了

**Comment by zhangxu19830126** [comment]
你能把你的配置和我看看么

**Comment by zhangxu19830126** [comment]
聚合API的定义

**Comment by hlj2722** [comment]
API Name: 用户聚合信息
    URL:   ^/api/users/(\d+)$
    Method: GET
    Status: UP
    Desc: 可空
    AccessControl: {"whitelist":null,"blacklist":null}
    Mock: null


![image](https://cloud.githubusercontent.com/assets/12218200/22766992/839cb3a6-eeb3-11e6-8ce9-1f86b8ac1746.png)

**Comment by hlj2722** [comment]
这个聚合API的定义是完全按照你的在线demo 设置的

**Comment by zhangxu19830126** [comment]
能把聚合API的dipatch nodes配置给我看看么

**Comment by hlj2722** [comment]
![image](https://cloud.githubusercontent.com/assets/12218200/22767112/63f72be8-eeb4-11e6-85e1-3ab12d86dda4.png)
是这个吧

**Comment by zhangxu19830126** [comment]
proxy的日志能帖上来么?

**Comment by hlj2722** [comment]
2017/02/09 10:21:25 log.go:33: [INFO] set log level to <info>
2017/02/09 10:21:25 proxy.go:51: [INFO] conf:<&{LogLevel:info Addr::80 MgrAddr::8081 EtcdAddrs:[http://127.0.0.1:2379] EtcdPrefix:/gateway Filers:[whitelist blacklist analysis rate-limiting circuit-breake http-access head xforward validation] PluginDir:/app/gateway/plugins ServiceDiscoveryDuration:10 MaxConns:512 MaxConnDuration:10 MaxIdleConnDuration:10 ReadBufferSize:4096 WriteBufferSize:4096 ReadTimeout:30 WriteTimeout:30 MaxResponseBodySize:104857600 EnablePPROF:false PPROFAddr:}>
2017/02/09 10:21:25 ruletable.go:515: [INFO] RouteTable start watch.
2017/02/09 10:21:25 etcd.go:425: [INFO] Etcd watch at: </gateway>
2017/02/09 10:21:25 ruletable.go:666: [WARN] Load clusters fail.
[error]: 100: Key not found (/gateway/clusters) [23213]
2017/02/09 10:21:25 ruletable.go:681: [WARN] Load servers from etcd fail.
[error]: 100: Key not found (/gateway/servers) [23213]
2017/02/09 10:21:25 ruletable.go:712: [WARN] Load binds from etcd fail.
[error]: 100: Key not found (/gateway/binds) [23213]
2017/02/09 10:21:25 ruletable.go:727: [WARN] Load apis from etcd fail.
[error]: 100: Key not found (/gateway/apis) [23213]
2017/02/09 10:21:25 ruletable.go:697: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/gateway/routings) [23213]
2017/02/09 10:21:25 manager.go:70: [INFO] Mgr listen at :8081.
2017/02/09 10:21:25 ruletable.go:624: [WARN] Load clusters from service discovery failure
[error]: Plugin not found

以下是启动的进程
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      450/etcd            
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      450/etcd
tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN      450/etcd            
tcp        0      0 127.0.0.1:4001          0.0.0.0:*               LISTEN      450/etcd
tcp6       0      0 :::8080                 :::*                    LISTEN      1675/./admin        
tcp6       0      0 :::8081                 :::*                    LISTEN      1679/./proxy 
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1679/./proxy
tcp        0      0 127.0.0.1:8888       0.0.0.0:*               LISTEN      1694/./backend

**Comment by zhangxu19830126** [comment]
proxy的日志就这么一点么？应该还有的吧。贴个完整的上来

**Comment by zhangxu19830126** [comment]
我看见你的proxy启动使用的etcd-prefix配置是：gateway ，而你的admin使用的是-etcd-prefix=dev，并不匹配？

**Comment by hlj2722** [comment]
2017/02/06 17:04:08 log.go:33: [INFO] set log level to <info>
2017/02/06 17:04:08 proxy.go:51: [INFO] conf:<&{LogLevel:info Addr::80 MgrAddr::8081 EtcdAddrs:[http://127.0.0.1:2379] EtcdPrefix:/gateway Filers:[whitelist blacklist analysis rate-limiting circuit-breake http-access head xforward validation] PluginDir:/app/gateway/plugins ServiceDiscoveryDuration:10 MaxConns:512 MaxConnDuration:10 MaxIdleConnDuration:10 ReadBufferSize:4096 WriteBufferSize:4096 ReadTimeout:30 WriteTimeout:30 MaxResponseBodySize:104857600 EnablePPROF:false PPROFAddr:}>
2017/02/06 17:04:08 ruletable.go:515: [INFO] RouteTable start watch.
2017/02/06 17:04:08 etcd.go:425: [INFO] Etcd watch at: </gateway>
2017/02/06 17:04:08 ruletable.go:666: [WARN] Load clusters fail.
[error]: 100: Key not found (/gateway/clusters) [2724]
2017/02/06 17:04:08 ruletable.go:681: [WARN] Load servers from etcd fail.
[error]: 100: Key not found (/gateway/servers) [2724]
2017/02/06 17:04:08 ruletable.go:712: [WARN] Load binds from etcd fail.
[error]: 100: Key not found (/gateway/binds) [2724]
2017/02/06 17:04:08 ruletable.go:727: [WARN] Load apis from etcd fail.
[error]: 100: Key not found (/gateway/apis) [2724]
2017/02/06 17:04:08 ruletable.go:697: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/gateway/routings) [2724]
2017/02/06 17:04:08 manager.go:70: [INFO] Mgr listen at :8081.
2017/02/06 17:04:08 ruletable.go:624: [WARN] Load clusters from service discovery failure
[error]: Plugin not found
2017/02/07 09:19:37 log.go:33: [INFO] set log level to <info>
2017/02/07 09:19:37 proxy.go:51: [INFO] conf:<&{LogLevel:info Addr::80 MgrAddr::8081 EtcdAddrs:[http://127.0.0.1:2379] EtcdPrefix:/gateway Filers:[whitelist blacklist analysis rate-limiting circuit-breake http-access head xforward validation] PluginDir:/app/gateway/plugins ServiceDiscoveryDuration:10 MaxConns:512 MaxConnDuration:10 MaxIdleConnDuration:10 ReadBufferSize:4096 WriteBufferSize:4096 ReadTimeout:30 WriteTimeout:30 MaxResponseBodySize:104857600 EnablePPROF:false PPROFAddr:}>
2017/02/07 09:19:37 ruletable.go:515: [INFO] RouteTable start watch.
2017/02/07 09:19:37 etcd.go:425: [INFO] Etcd watch at: </gateway>
2017/02/07 09:19:37 ruletable.go:666: [WARN] Load clusters fail.
[error]: 100: Key not found (/gateway/clusters) [6796]
2017/02/07 09:19:37 ruletable.go:681: [WARN] Load servers from etcd fail.
[error]: 100: Key not found (/gateway/servers) [6796]
2017/02/07 09:19:37 ruletable.go:712: [WARN] Load binds from etcd fail.
[error]: 100: Key not found (/gateway/binds) [6796]
2017/02/07 09:19:37 ruletable.go:727: [WARN] Load apis from etcd fail.
[error]: 100: Key not found (/gateway/apis) [6796]
2017/02/07 09:19:37 ruletable.go:697: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/gateway/routings) [6796]
2017/02/07 09:19:37 manager.go:70: [INFO] Mgr listen at :8081.
2017/02/07 09:19:37 ruletable.go:624: [WARN] Load clusters from service discovery failure
[error]: Plugin not found
2017/02/09 09:23:58 log.go:33: [INFO] set log level to <info>
2017/02/09 09:23:58 proxy.go:51: [INFO] conf:<&{LogLevel:info Addr::80 MgrAddr::8081 EtcdAddrs:[http://127.0.0.1:2379] EtcdPrefix:/gateway Filers:[whitelist blacklist analysis rate-limiting circuit-breake http-access head xforward validation] PluginDir:/app/gateway/plugins ServiceDiscoveryDuration:10 MaxConns:512 MaxConnDuration:10 MaxIdleConnDuration:10 ReadBufferSize:4096 WriteBufferSize:4096 ReadTimeout:30 WriteTimeout:30 MaxResponseBodySize:104857600 EnablePPROF:false PPROFAddr:}>
2017/02/09 09:23:58 ruletable.go:515: [INFO] RouteTable start watch.
2017/02/09 09:23:58 etcd.go:425: [INFO] Etcd watch at: </gateway>
2017/02/09 09:23:58 ruletable.go:666: [WARN] Load clusters fail.
[error]: 100: Key not found (/gateway/clusters) [22051]
2017/02/09 09:23:58 ruletable.go:681: [WARN] Load servers from etcd fail.
[error]: 100: Key not found (/gateway/servers) [22051]
2017/02/09 09:23:58 ruletable.go:712: [WARN] Load binds from etcd fail.
[error]: 100: Key not found (/gateway/binds) [22051]
2017/02/09 09:23:58 ruletable.go:727: [WARN] Load apis from etcd fail.
[error]: 100: Key not found (/gateway/apis) [22051]
2017/02/09 09:23:58 ruletable.go:697: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/gateway/routings) [22051]
2017/02/09 09:23:58 manager.go:70: [INFO] Mgr listen at :8081.
2017/02/09 09:23:58 ruletable.go:624: [WARN] Load clusters from service discovery failure
[error]: Plugin not found
2017/02/09 10:21:25 log.go:33: [INFO] set log level to <info>
2017/02/09 10:21:25 proxy.go:51: [INFO] conf:<&{LogLevel:info Addr::80 MgrAddr::8081 EtcdAddrs:[http://127.0.0.1:2379] EtcdPrefix:/gateway Filers:[whitelist blacklist analysis rate-limiting circuit-breake http-access head xforward validation] PluginDir:/app/gateway/plugins ServiceDiscoveryDuration:10 MaxConns:512 MaxConnDuration:10 MaxIdleConnDuration:10 ReadBufferSize:4096 WriteBufferSize:4096 ReadTimeout:30 WriteTimeout:30 MaxResponseBodySize:104857600 EnablePPROF:false PPROFAddr:}>
2017/02/09 10:21:25 ruletable.go:515: [INFO] RouteTable start watch.
2017/02/09 10:21:25 etcd.go:425: [INFO] Etcd watch at: </gateway>
2017/02/09 10:21:25 ruletable.go:666: [WARN] Load clusters fail.
[error]: 100: Key not found (/gateway/clusters) [23213]
2017/02/09 10:21:25 ruletable.go:681: [WARN] Load servers from etcd fail.
[error]: 100: Key not found (/gateway/servers) [23213]
2017/02/09 10:21:25 ruletable.go:712: [WARN] Load binds from etcd fail.
[error]: 100: Key not found (/gateway/binds) [23213]
2017/02/09 10:21:25 ruletable.go:727: [WARN] Load apis from etcd fail.
[error]: 100: Key not found (/gateway/apis) [23213]
2017/02/09 10:21:25 ruletable.go:697: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/gateway/routings) [23213]
2017/02/09 10:21:25 manager.go:70: [INFO] Mgr listen at :8081.
2017/02/09 10:21:25 ruletable.go:624: [WARN] Load clusters from service discovery failure
[error]: Plugin not found

所有的日志都在这了

**Comment by zhangxu19830126** [comment]
我觉得是你的proxy和admin的etcd-prefix参数配置不一致，proxy并没有加载到任何Cluster，server,API的元数据啊

**Comment by zhangxu19830126** [comment]
我登上去了，你的所有配置都是空的啊

**Comment by zhangxu19830126** [comment]
![image](https://cloud.githubusercontent.com/assets/2995754/22767793/b1915abe-eeb8-11e6-8fc5-c81f68bdfa57.png)

**Comment by zhangxu19830126** [comment]
你应该把你的proxy和admin都适用-etcd-prefix=dev的配置，你之前在 admin上配置的都是基于-etcd-prefix=dev这个配置的

**Comment by hlj2722** [comment]
应该是 -etcd-prefix  重新设置的原因，我再设置看看

**Comment by zhangxu19830126** [comment]
你要修改你的proxy的配置文件，修改为etcd-prefix=dev

**Comment by hlj2722** [comment]
嗯，已经都 设置回dev了，你再看看

**Comment by zhangxu19830126** [comment]
![image](https://cloud.githubusercontent.com/assets/2995754/22767879/515f001e-eeb9-11e6-809d-59980585c9f2.png)
这里的backend server地址对么

**Comment by zhangxu19830126** [comment]
你应该能在proxy的日志里面看见，proxy尝试去check这个server

**Comment by zhangxu19830126** [comment]
看看有没有check成功

**Comment by hlj2722** [comment]
backend 启动 ./backend --addr 120.24.185.8:9091
还是 check 失败 ，以下是最后的日志

2017/02/09 11:15:14 log.go:33: [INFO] set log level to <info>
2017/02/09 11:15:14 proxy.go:51: [INFO] conf:<&{LogLevel:info Addr::80 MgrAddr::8081 EtcdAddrs:[http://127.0.0.1:2379] EtcdPrefix:/dev Filers:[whitelist blacklist analysis rate-limiting circuit-breake http-access head xforward validation] PluginDir:/app/gateway/plugins ServiceDiscoveryDuration:10 MaxConns:512 MaxConnDuration:10 MaxIdleConnDuration:10 ReadBufferSize:4096 WriteBufferSize:4096 ReadTimeout:30 WriteTimeout:30 MaxResponseBodySize:104857600 EnablePPROF:false PPROFAddr:}>
2017/02/09 11:15:14 ruletable.go:515: [INFO] RouteTable start watch.
2017/02/09 11:15:14 etcd.go:425: [INFO] Etcd watch at: </dev>
2017/02/09 11:15:14 ruletable.go:382: [INFO] Cluster <demo-app> added
2017/02/09 11:15:14 analysis.go:169: [INFO] Analysis <120.24.185.8:8081,1> added
2017/02/09 11:15:14 analysis.go:148: [INFO] Analysis already <120.24.185.8:8081,1> added
2017/02/09 11:15:14 analysis.go:169: [INFO] Analysis <120.24.185.8:8081,3> added
2017/02/09 11:15:14 ruletable.go:320: [INFO] Server <120.24.185.8:8081> added
2017/02/09 11:15:14 ruletable.go:414: [INFO] Bind <120.24.185.8:8081,demo-app> stored.
2017/02/09 11:15:14 ruletable.go:190: [INFO] API <GET-/api/users/\d+/account> added
2017/02/09 11:15:14 ruletable.go:190: [INFO] API <GET-/api/users/\d+/base> added
2017/02/09 11:15:14 ruletable.go:190: [INFO] API <GET-^/api/users/(\d+)$> added
2017/02/09 11:15:14 ruletable.go:190: [INFO] API <GET-check> added
2017/02/09 11:15:14 ruletable.go:697: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/dev/routings) [24283]
2017/02/09 11:15:14 manager.go:70: [INFO] Mgr listen at :8081.
2017/02/09 11:15:14 ruletable.go:624: [WARN] Load clusters from service discovery failure
[error]: Plugin not found
2017/02/09 11:15:17 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 1> check fail.
2017/02/09 11:15:21 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 2> check fail.
2017/02/09 11:15:27 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 3> check fail.
2017/02/09 11:15:36 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 4> check fail.
2017/02/09 11:15:49 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 5> check fail.
2017/02/09 11:16:08 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 6> check fail.
2017/02/09 11:16:36 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 7> check fail.
2017/02/09 11:17:18 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 8> check fail.
2017/02/09 11:18:21 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 9> check fail.
2017/02/09 11:19:55 server.go:237: [WARN] Server <120.24.185.8:8081, /check, 10> check fail.
2017/02/09 11:20:39 etcd.go:475: [INFO] Etcd changed: </dev/binds/120.24.185.8:8081-demo-app, delete>
2017/02/09 11:20:39 ruletable.go:448: [INFO] Bind <120.24.185.8:8081,demo-app> stored removed.
2017/02/09 11:20:39 cluster.go:136: [INFO] UnBind <120.24.185.8:8081,demo-app> succ.
2017/02/09 11:20:39 etcd.go:475: [INFO] Etcd changed: </dev/servers/120.24.185.8:8081, set>
2017/02/09 11:20:39 analysis.go:148: [INFO] Analysis already <120.24.185.8:8081,1> added
2017/02/09 11:20:39 analysis.go:148: [INFO] Analysis already <120.24.185.8:8081,1> added
2017/02/09 11:20:39 server.go:163: [INFO] Server <120.24.185.8:8081> updated, &{Schema:http Addr:120.24.185.8:8081 External:false CheckPath:/check CheckResponsedBody: CheckDuration:3 CheckTimeout:3 Status:0 MaxQPS:100 HalfToOpenSeconds:10 HalfTrafficRate:10 HalfToOpenSucceedRate:80 HalfToOpenCollectSeconds:3 OpenToCloseFailureRate:30 OpenToCloseCollectSeconds:1 BindClusters:[demo-app] httpClient:0xc4201404e0 checkFailCount:10 prevStatus:0 useCheckDuration:141 circuit:0 lock:0xc42011f9d0 checkStopped:false}
2017/02/09 11:20:39 ruletable.go:246: [INFO] Server <120.24.185.8:8081> updated
2017/02/09 11:20:39 etcd.go:475: [INFO] Etcd changed: </dev/clusters/demo-app, set>
2017/02/09 11:20:39 cluster.go:114: [INFO] Cluster <demo-app> updated, &{Name:demo-app LbName:ROUNDROBIN External:false BindServers:[120.24.185.8:8081] svrs:0xc420117fb0 rwLock:0xc42011d060 lb:{ops:0xc420182890}}
2017/02/09 11:20:39 ruletable.go:338: [INFO] Cluster <demo-app> updated
2017/02/09 11:20:47 etcd.go:475: [INFO] Etcd changed: </dev/servers/120.24.185.8:8081, delete>
2017/02/09 11:20:47 ruletable.go:271: [INFO] Bind <120.24.185.8:8081> stored all removed.
2017/02/09 11:20:47 ruletable.go:277: [INFO] Server <120.24.185.8:8081> deleted
2017/02/09 11:22:01 etcd.go:475: [INFO] Etcd changed: </dev/servers/120.24.185.8:9091, create>
2017/02/09 11:22:01 analysis.go:169: [INFO] Analysis <120.24.185.8:9091,1> added
2017/02/09 11:22:01 analysis.go:148: [INFO] Analysis already <120.24.185.8:9091,1> added
2017/02/09 11:22:01 analysis.go:169: [INFO] Analysis <120.24.185.8:9091,3> added
2017/02/09 11:22:01 ruletable.go:320: [INFO] Server <120.24.185.8:9091> added
2017/02/09 11:22:03 ruletable.go:754: [INFO] Server <120.24.185.8:9091> UP.
2017/02/09 11:22:17 etcd.go:475: [INFO] Etcd changed: </dev/binds/120.24.185.8:9091-demo-app, create>
2017/02/09 11:22:17 ruletable.go:414: [INFO] Bind <120.24.185.8:9091,demo-app> stored.
2017/02/09 11:22:17 cluster.go:150: [INFO] Bind <120.24.185.8:9091,demo-app> created.
2017/02/09 11:22:17 etcd.go:475: [INFO] Etcd changed: </dev/servers/120.24.185.8:9091, set>
2017/02/09 11:22:17 analysis.go:148: [INFO] Analysis already <120.24.185.8:9091,1> added
2017/02/09 11:22:17 analysis.go:148: [INFO] Analysis already <120.24.185.8:9091,1> added
2017/02/09 11:22:17 server.go:163: [INFO] Server <120.24.185.8:9091> updated, &{Schema:http Addr:120.24.185.8:9091 External:false CheckPath:/check CheckResponsedBody: CheckDuration:3 CheckTimeout:3 Status:1 MaxQPS:100 HalfToOpenSeconds:10 HalfTrafficRate:10 HalfToOpenSucceedRate:30 HalfToOpenCollectSeconds:3 OpenToCloseFailureRate:30 OpenToCloseCollectSeconds:1 BindClusters:[] httpClient:0xc4201c00c0 checkFailCount:3 prevStatus:1 useCheckDuration:9 circuit:0 lock:0xc42023bc40 checkStopped:false}
2017/02/09 11:22:17 ruletable.go:246: [INFO] Server <120.24.185.8:9091> updated
2017/02/09 11:22:17 etcd.go:475: [INFO] Etcd changed: </dev/clusters/demo-app, set>
2017/02/09 11:22:17 cluster.go:114: [INFO] Cluster <demo-app> updated, &{Name:demo-app LbName:ROUNDROBIN External:false BindServers:[120.24.185.8:8081] svrs:0xc420117fb0 rwLock:0xc42011d060 lb:{ops:0xc4201496b0}}
2017/02/09 11:22:17 ruletable.go:338: [INFO] Cluster <demo-app> updated
2017/02/09 11:26:47 log.go:33: [INFO] set log level to <info>
2017/02/09 11:26:47 proxy.go:51: [INFO] conf:<&{LogLevel:info Addr::80 MgrAddr::8081 EtcdAddrs:[http://127.0.0.1:2379] EtcdPrefix:/dev Filers:[whitelist blacklist analysis rate-limiting circuit-breake http-access head xforward validation] PluginDir:/app/gateway/plugins ServiceDiscoveryDuration:10 MaxConns:512 MaxConnDuration:10 MaxIdleConnDuration:10 ReadBufferSize:4096 WriteBufferSize:4096 ReadTimeout:30 WriteTimeout:30 MaxResponseBodySize:104857600 EnablePPROF:false PPROFAddr:}>
2017/02/09 11:26:47 ruletable.go:515: [INFO] RouteTable start watch.
2017/02/09 11:26:47 etcd.go:425: [INFO] Etcd watch at: </dev>
2017/02/09 11:26:47 ruletable.go:382: [INFO] Cluster <demo-app> added
2017/02/09 11:26:47 analysis.go:169: [INFO] Analysis <120.24.185.8:9091,1> added
2017/02/09 11:26:47 analysis.go:148: [INFO] Analysis already <120.24.185.8:9091,1> added
2017/02/09 11:26:47 analysis.go:169: [INFO] Analysis <120.24.185.8:9091,3> added
2017/02/09 11:26:47 ruletable.go:320: [INFO] Server <120.24.185.8:9091> added
2017/02/09 11:26:47 ruletable.go:414: [INFO] Bind <120.24.185.8:9091,demo-app> stored.
2017/02/09 11:26:47 ruletable.go:190: [INFO] API <GET-/api/users/\d+/account> added
2017/02/09 11:26:47 ruletable.go:190: [INFO] API <GET-/api/users/\d+/base> added
2017/02/09 11:26:47 ruletable.go:190: [INFO] API <GET-^/api/users/(\d+)$> added
2017/02/09 11:26:47 ruletable.go:190: [INFO] API <GET-check> added
2017/02/09 11:26:47 ruletable.go:697: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/dev/routings) [24513]
2017/02/09 11:26:47 manager.go:70: [INFO] Mgr listen at :8081.
2017/02/09 11:26:47 ruletable.go:624: [WARN] Load clusters from service discovery failure
[error]: Plugin not found
2017/02/09 11:26:50 server.go:237: [WARN] Server <120.24.185.8:9091, /check, 1> check fail.
2017/02/09 11:26:54 server.go:237: [WARN] Server <120.24.185.8:9091, /check, 2> check fail.
2017/02/09 11:27:00 server.go:237: [WARN] Server <120.24.185.8:9091, /check, 3> check fail.
2017/02/09 11:27:09 ruletable.go:754: [INFO] Server <120.24.185.8:9091> UP.
2017/02/09 11:27:09 cluster.go:150: [INFO] Bind <120.24.185.8:9091,demo-app> created.

**Comment by zhangxu19830126** [comment]
![image](https://cloud.githubusercontent.com/assets/2995754/22768179/42285012-eebb-11e6-82ea-aecfe95a75db.png)
成功了啊

**Comment by hlj2722** [comment]
http://120.24.185.8:9091/api/users/1 这个访问没访问到数据啊

![image](https://cloud.githubusercontent.com/assets/12218200/22768203/6dfcabde-eebb-11e6-8425-837f1fd96081.png)

**Comment by zhangxu19830126** [comment]
使用proxy的端口访问：

**Comment by zhangxu19830126** [comment]
http://120.24.185.8/api/users/1/account,http://120.24.185.8/api/users/1/base,http://120.24.185.8/api/users/1

**Comment by hlj2722** [comment]
可以了，非常感谢。顺便问下，我可以参与到你的项目中吗和你一起开发

**Comment by zhangxu19830126** [comment]
你擅长什么？

**Comment by hlj2722** [comment]
在公司项目中使用 beego 做过restful api,和cli 开发
