### ISSUE TITLE
咨询：转发请求时如何添加额外的 header 字段

### ISSUE THREAD

**Issue by dantin-s** [fagongzi/gateway#100]
问题描述：我需要在请求转发到后端 server 的时候在 Header 中加上 Host 字段，实现 nginx 中 proxy_set_header 的效果，请问要怎么配置？

看了下源码，直接就设置了 Host 头为 server 的 addr？
https://github.com/fagongzi/gateway/blob/12f6d3f2d67b3eb3ff6ff1877e176e1b6f5be3f5/pkg/proxy/filter_headers.go#L43

**Comment by zhangxu19830126** [comment]
proxy会复制header到后端，如果需要添加自定义的header，目前不支持，可以自己写filter插件来实现

**Comment by dantin-s** [comment]
> proxy会复制header到后端，如果需要添加自定义的header，目前不支持，可以自己写filter插件来实现

举个实例深入请教下：
request(www.abc.com) ->  gateway proxy -> server(192.168.0.1)
我理解，request 头里面带的 Host 应该是 www.abc.com，proxy 里面把这个字段设置为了 192.168.0.1，所以这里应该不能说是复制了 header。从我的角度理解的话，原始的 Host 就是正确的，不需要重新设置，您觉得呢？

**Comment by zhangxu19830126** [comment]
我觉得看需求了，这个是api gateway，后面的都是http restful服务，这些服务需要关心host么？
