### ISSUE TITLE
docker run fagongzi/apiserver 无法连接etcd

### ISSUE THREAD

**Issue by FrankHitman** [fagongzi/gateway#102]
$ docker run fagongzi/apiserver:latest
2018/10/09 12:26:42.616419 [info] addr: 127.0.0.1:9092
2018/10/09 12:26:42.616454 [info] addr-store: etcd://127.0.0.1:2379
2018/10/09 12:26:42.616456 [info] namespace: dev
2018/10/09 12:26:42.616458 [info] discovery: false
2018/10/09 12:26:42.616459 [info] service-prefix: /services
2018/10/09 12:26:42.616461 [info] publish-lease: 10
2018/10/09 12:26:42.616462 [info] publish-timeout: 30
2018/10/09 12:26:45.617257 [fatal] init store failed for etcd://127.0.0.1:2379, errors:
dial tcp 127.0.0.1:2379: connect: connection refused
经过调研，使用的是 "github.com/coreos/etcd/clientv3"包中的clientv3连接etcd的，自己写了个代码如下
`
package main

import (
	"fmt"
	//"go.etcd.io/etcd/clientv3"
	"github.com/coreos/etcd/clientv3"

	"os"
	"time"
)

func main() {
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"localhost:2379"},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		fmt.Println(err)
		// handle error!
		os.Exit(1)
	}
	fmt.Println("success")
	defer cli.Close()
}
`
也是报错，经查需要把包改为"go.etcd.io/etcd/clientv3"才正常。估计是这个包名改名字导致的，然后我把fagongzi/gateway代码中所以地方，包括vendor中的包名引用都更改了，重新编译成docker镜像，编译都不通过。作者这个地方是如何起这个服务的？

**Comment by FrankHitman** [comment]
考虑到是不是etcd的版本问题，但是etcd 使用3.1.19和3.3.9两个版本启动服务端都不行。

**Comment by zhangxu19830126** [comment]
你在docker内部启动proxy,链接的是127.0.0.1的etcd，你docker容器内部有etcd？你链接的是外部etcd，请修改你的etcd链接地址
