### ISSUE TITLE
health check 锁的时间过长

### ISSUE THREAD

**Issue by phhong** [fagongzi/gateway#111]
check方法中持有写锁的时间包含了调用back-end服务的健康检查接口的时间。
当back-end down的时候，如果超时设置得比较长，那么持有写锁的时间也就较长。而转发的时候也会申请同一个锁的读锁，会被block住较长的时间。

偶然也会有死锁，应该和heathCheckTimeout方法中也申请了锁有关。Schedule方法在偶然的情况下会直接执行heathCheckTimeout，而不是由另一个goroutine执行，导致没有释放锁就先申请锁了。

func (r *dispatcher) heathCheckTimeout(arg interface{}) {
	id := arg.(uint64)
	r.RLock()
	_, ok := r.servers[id]
	r.RUnlock()
	if ok {
		r.checkerC <- id
	}
}

func (r *dispatcher) check(id uint64) {
	r.RLock()
	defer r.RUnlock()
	svr, ok := r.servers[id]
	if !ok {
		return
	}

	defer func() {
		if svr.meta.HeathCheck != nil {
			if svr.useCheckDuration > r.cnf.Option.LimitIntervalHeathCheck {
				svr.useCheckDuration = r.cnf.Option.LimitIntervalHeathCheck
			}
			svr.heathTimeout, _ = r.tw.Schedule(svr.useCheckDuration, r.heathCheckTimeout, id)
		}
	}()

**Comment by zhangxu19830126** [comment]
健康检查使用的是读锁，读锁和读锁之间不会发生冲突，我不认为你说的是个问题

**Comment by phhong** [comment]
哈哈，不好意思，我看的还是几个月前拉的旧版本的代码，倒是贴了新版本的。嗯，原来已经改过啦，没有注意。

**Comment by phhong** [comment]
改用了读锁之后，仍然出现死锁现象。请问一下heathCheckTimeout方法中是否可以去除读锁？

**Comment by zhangxu19830126** [comment]
有没有详细的日志？我这边不能复现这个问题

**Comment by phhong** [comment]
这个问题不常出现，试了很多次大概也就出现过1、2次，由于环境重新装了，日志也没有了，就是dispatcher的dispatch方法第一行的r.RLock()前后都加上log，只有前面的打出来了，后面的一直出不来。

看RWMutex的文档，确实也提到不可以用于recursive reading的，不知道是不是指一个goroutine中不可以在释放读锁之前aquire同一个锁（重入）。看代码，有概率会发生重入。
