### ISSUE TITLE
Demo & Pics

### ISSUE THREAD

**Issue by CatsPlugins** [fagongzi/gateway#121]
Hello,

Do you have any demo for your gateway admin UI?

It's not in English so it's hard for me to understand all the features.

Can I limit the API by API key? Do we have the API consumer?

Thanks!

**Comment by zhangxu19830126** [comment]
Hi,
We don't currently support English, you can use google translation for the time being, we expect to provide English documents this year.

Can I limit the API by API key?  
Yes, rate limiting and circuit breaker in the definition of the API.

Do we have the API consumer? 
I don't understand what you mean, what is the API consumer?

**Comment by zhangxu19830126** [comment]
Do you have any demo for your gateway admin UI?
you can using docker as below:
1  `docker pull fagongzi/gateway`
2 `docker run -d --rm -p 80:80 -p 9093:9093 -p 9092:9092 fagongzi/gateway`
3. `http://127.0.0.1:9093/ui/index.html` to access WEBUI
4. The port `80` is the entrypoint for clients.
