### ISSUE TITLE
Support for standard request id in logging

### ISSUE THREAD

**Issue by h662607** [fagongzi/gateway#123]
你好，我们在尝试使用 gateway 项目，在做测试时发现日志中不带有 request id 此类能够标记特定请求的日志信息，排查问题时成本会提高（尤其单位时间内请求数量较多时），请问下作者在日常使用中是如何解决的呢？后续是否有支持 request id 记录这样的计划呢？我们很愿意在这方面提供帮助。

**Comment by zhangxu19830126** [comment]
我正在计划添加opentracing支持

**Comment by h662607** [comment]
了解了，感谢回复。
