### ISSUE TITLE
快速体验

### ISSUE THREAD

**Issue by aaaasssdd** [fagongzi/gateway#128]
启动docker run -d -p 9093:9093 -p 80:80 -p 9092:9092 fagongzi/gateway

**Comment by aaaasssdd** [comment]
然后通过ui设置cluster,server 访问提示not match, return with 404。   哪里配置缺少了呢？

**Comment by zhangxu19830126** [comment]
请参考 https://github.com/fagongzi/gateway/blob/master/docs/user-guide.md

**Comment by aaaasssdd** [comment]
非常感谢回复，我参考设置了cluster,server

2019/05/05 10:37:27.951715 [info] bind <1,4> created
2019/05/05 10:40:27.195772 [info] api <5> added, data <id:5 name:"\357\277\275\357\277\275\321\257\357\277\275\326\261\357\277\275\357\277\275\357\277\275\317\242\357\277\275\323\277\357\277\275" urlPattern:"^/liebao/.*$" method:"GET" status:Up nodes:<clusterID:1 > >
2019/05/05 10:40:37.123607 [info] [GET]/liebao/ws/v1/wifilist: match api 锟斤拷询锟街憋拷锟斤拷息锟接匡拷, has 1 dispatches
2019/05/05 10:40:37.123752 [info] [GET]/liebao/ws/v1/wifilist: dipatch node 0 sent for 0 times
2019/05/05 10:40:37.152690 [error] [GET]/liebao/ws/v1/wifilist: dipatch node 0 failed with error code 404
2019/05/05 10:43:58.941086 [info] api <6> added, data <id:6 name:"\357\277\275\357\277\275\321\257\357\277\275\326\261\357\277\275\357\277\275\357\277\275\317\242\357\277\275\323\277\357\277\275" urlPattern:"^/liebao/ws/v1/wifilist" method:"GET" status:Up nodes:<clusterID:1 > >
2019/05/05 10:44:06.975135 [info] [GET]/liebao/ws/v1/wifilist: match api 锟斤拷询锟街憋拷锟斤拷息锟接匡拷, has 1 dispatches
2019/05/05 10:44:06.975210 [info] [GET]/liebao/ws/v1/wifilist: dipatch node 0 sent for 0 times
2019/05/05 10:44:07.005987 [error] [GET]/liebao/ws/v1/wifilist: dipatch node 0 failed with error code 404

**Comment by aaaasssdd** [comment]
是每个url都需要设置吗？ 应该怎么设置呢。

**Comment by aaaasssdd** [comment]
这个问题我先关闭吧，我再研究一下。
