### ISSUE TITLE
关于JWTFilter

### ISSUE THREAD

**Issue by aaaasssdd** [fagongzi/gateway#130]
我看了一下代码，这个filter是检查token的吧。

麻烦问两个问题
1、认证是怎么设计的呢？
2、过期处理机制是什么样的？

**Comment by zhangxu19830126** [comment]
1. 认证就是根据token认证，同时可以检查token是否存在于redis中（token发放应用写入redis）。

**Comment by aaaasssdd** [comment]
token发放是后台应用完成的吧，网管只是提取检查，是这样吗？ 哪检查的逻辑和发放的逻辑是约定的吗？

**Comment by zhangxu19830126** [comment]
是约定的，如果后端不满足，可以自己写插件代替默认的JWT插件

**Comment by aaaasssdd** [comment]
好的，多谢。
