### ISSUE TITLE
咱们这个打包，能不能打包成二进制的可执行文件，方便部署，很多项目都是这么做的

### ISSUE THREAD

**Issue by lchjczw** [fagongzi/gateway#134]
咱们这个打包，能不能打包成二进制的可执行文件，方便部署，很多项目都是这么做的

**Comment by zhangxu19830126** [comment]
https://github.com/fagongzi/gateway/blob/master/docs/build.md

**Comment by lchjczw** [comment]
嗯，我用docker先测试，快速体验这个部署后，提示访问被拒绝

**Comment by zhangxu19830126** [comment]
先把docs文档看一遍
