### ISSUE TITLE
admin创建api时没有Domain参数

### ISSUE THREAD

**Issue by weisd** [fagongzi/gateway#15]
admin创建api时没有Domain参数， 判断api.match时会判断Domain

**Comment by zhangxu19830126** [comment]
这个参数的意义是用来按照domain匹配后端服务（目前的匹配模式是按照URL和Method来匹配），这个特性还没有搞完，最近2个月实在是太忙了

**Comment by weisd** [comment]
@zhangxu19830126 有具体的需求文档吗？有时间我可以帮写

**Comment by zhangxu19830126** [comment]
@weisd 加我微信，我们细聊。13675153174
