### ISSUE TITLE
咨询多域名和证书绑定的功能

### ISSUE THREAD

**Issue by jeffbmob** [fagongzi/gateway#160]
用户上传自己的ssl证书到我方的服务器，我方帮用户把https证书和域名部署到入口服务器，这样用户就能使用自己的域名通过https来访问我方提供的服务了。这样必须做到动态加载证书和域名 ，达到用户一旦上传就能马上部署好的效果。另一方面，用户可能很多，导致上传的证书也很多，如果新增域名都要重启入口服务器，可能非常慢，所以要有动态加载的功能。

请问gateway这个软件，能实现上面入口服务器的需求吗？

**Comment by zhangxu19830126** [comment]
gateway支持上传证书不重启，可以为每个API绑定不一样的证书。这个功能还是实验性质，还没有生产使用案例
