### ISSUE TITLE
自定义首字母为小写的Header属性头，经过网关会转成标准头属性格式（首字母大写）

### ISSUE THREAD

**Issue by softwarelife** [fagongzi/gateway#165]
![图片](https://user-images.githubusercontent.com/3872198/63579190-a12f3c00-c5c4-11e9-9da7-299e039dea3f.png)

如图，请求网关header头属性中有首字母为小写的自定义属性，经过网关proxy后转发到server端的请求中，header头中的属性名称首字母都按照标准化命名方式转化成了大写。
如下图：

![图片](https://user-images.githubusercontent.com/3872198/63579752-f28bfb00-c5c5-11e9-9cc3-4d4a4cd9ca1e.png)

**Comment by zhangxu19830126** [comment]
proxy启动的时候，加上--disable-header-normalizing参数

**Comment by zhangxu19830126** [comment]
同时建议如果可以修改的话，请遵循http1.1的header名称的标准
