### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by xinzf** [fagongzi/gateway#169]
2019/09/22 22:53:10.017435 [info] [GET]/department/49: match api department, has 1 dispatches
2019/09/22 22:53:10.017457 [info] [GET]/department/49: dipatch node 0 force using default
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x181c65d]

goroutine 137 [running]:
github.com/fagongzi/gateway/pkg/proxy.(*dispatchNode).getResponseBody(0xc000498160, 0x0, 0x0, 0x100000000000008)
	/Users/xiangzhi/Work/Go/src/github.com/fagongzi/gateway/pkg/proxy/dispatcher.go:159 +0x4d
github.com/fagongzi/gateway/pkg/proxy.(*render).renderRaw(0xc000330540, 0xc00040c480, 0xc000498160)
	/Users/xiangzhi/Work/Go/src/github.com/fagongzi/gateway/pkg/proxy/render.go:135 +0xcf
github.com/fagongzi/gateway/pkg/proxy.(*render).renderSingle(0xc000330540, 0xc00040c480)
	/Users/xiangzhi/Work/Go/src/github.com/fagongzi/gateway/pkg/proxy/render.go:74 +0x1a0
github.com/fagongzi/gateway/pkg/proxy.(*render).render(0xc000330540, 0xc00040c480, 0x0)
	/Users/xiangzhi/Work/Go/src/github.com/fagongzi/gateway/pkg/proxy/render.go:51 +0xee
github.com/fagongzi/gateway/pkg/proxy.(*Proxy).ServeFastHTTP(0xc00027c000, 0xc00040c480)
	/Users/xiangzhi/Work/Go/src/github.com/fagongzi/gateway/pkg/proxy/proxy.go:318 +0xb96
github.com/valyala/fasthttp.(*Server).serveConn(0xc000486000, 0x1bcc420, 0xc000376030, 0x0, 0x0)
	/Users/xiangzhi/Work/Go/src/github.com/fagongzi/gateway/vendor/github.com/valyala/fasthttp/server.go:1932 +0x824
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00037a2d0, 0xc000326d40)
	/Users/xiangzhi/Work/Go/src/github.com/fagongzi/gateway/vendor/github.com/valyala/fasthttp/workerpool.go:212 +0xc0
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc00037a2d0, 0xc000326d40, 0x18bf020, 0xc000326d40)
	/Users/xiangzhi/Work/Go/src/github.com/fagongzi/gateway/vendor/github.com/valyala/fasthttp/workerpool.go:184 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/Users/xiangzhi/Work/Go/src/github.com/fagongzi/gateway/vendor/github.com/valyala/fasthttp/workerpool.go:183 +0x119

**Comment by zhangxu19830126** [comment]
设置了强制使用默认值，但是默认值没有配置，看下这个API的元数据配置呢

**Comment by xinzf** [comment]
> 设置了强制使用默认值，但是默认值没有配置，看下这个API的元数据配置呢

按您的指引已解决，貌似是一个小bug，还原一下操作：
1、API设置中，开启了”强制启用默认值“
2、然后又移除了这个HTTP默认值设置

预期结果：该默认值设置被移除，不应该其作用
实际结果：系统识别了“强制启用默认值”，但是该默认值数据被删除

**Comment by bosscheng** [comment]
@xinzf 谢谢提出问题。

**Comment by xinzf** [comment]
> @xinzf 谢谢提出问题。

you are welcome
