### ISSUE TITLE
能不能加点注释，介绍下几个主要struct 中的字段都是干吗用呢

### ISSUE THREAD

**Issue by ocoderr** [fagongzi/gateway#170]
你好。
能不能介绍下请求主要的处理流程是什么样的？
谢谢

**Comment by zhangxu19830126** [comment]
https://github.com/fagongzi/gateway/blob/master/images/flow.png

**Comment by ocoderr** [comment]
老哥, 我看代码，发现有用到  *goetty.TimeoutWheel 这个东。 感觉是在做个定时执行的东西。 老哥能介绍下这个里面是怎么个逻辑么？
