### ISSUE TITLE
操作视频可以放在bilibili上么

### ISSUE THREAD

**Issue by erha367** [fagongzi/gateway#173]
大佬你好，操作视频可以放在bilibili上么？

**Comment by BruceWangNo1** [comment]
可以。我明天传上去。

**Comment by BruceWangNo1** [comment]
Github项目fagongzi/gateway（API网关）教程：https://www.bilibili.com/video/av73432556/
【教程】Github项目fagongzi/gateway（API网关）路由配置： https://www.bilibili.com/video/av73432836/
【教程】Github项目fagongzi/gateway（API网关）JWT插件配置： https://www.bilibili.com/video/av73433002/

@erha367

**Comment by erha367** [comment]
谢谢大佬、
