### ISSUE TITLE
启动proxy失败

### ISSUE THREAD

**Issue by coldlin** [fagongzi/gateway#179]
2019/11/12 14:43:40.065824 [info] filter added, filter=<XFORWARD>
2019/11/12 14:43:40.065824 [info] filter added, filter=<VALIDATION>
2019/11/12 14:43:40.065824 [info] filter added, filter=<JS-Plugin-Engine>
2019/11/12 14:43:50.066397 [fatal] init route table failed, errors:
context deadline exceeded

**Comment by zhangxu19830126** [comment]
proxy can not connect to etcd server.
