### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by colinwdk** [fagongzi/gateway#2]
您好，对这个项目不是很了解，可能在配置上有点问题，不知道是怎么回事，麻烦帮忙指点下，多谢。
我的环境下：
**## gateway的log如下：**
2016/06/30 19:57:18 log.go:31: [INFO] set log level to <info>
2016/06/30 19:57:18 gateway.go:68: [INFO] conf:<&{Addr::80 MgrAddr::8081 EtcdAddr:http://127.0.0.1:2379 EtcdPrefix:/gateway LogLevel:info EnableRuntimeVal:false EnableCookieVal:false EnableHeadVal:false ReqHeadStaticMapping:map[] RspHeadStaticMapping:map[]}>
2016/06/30 19:57:18 ruletable.go:467: [INFO] RouteTable start watch.
2016/06/30 19:57:18 etcd.go:379: [INFO] Etcd watch at: </gateway>
2016/06/30 19:57:18 ruletable.go:564: [WARN] Load clusters fail.
[error]: 100: Key not found (/gateway) [5]
2016/06/30 19:57:18 ruletable.go:579: [WARN] Load servers from etcd fail.
[error]: 100: Key not found (/gateway) [5]
2016/06/30 19:57:18 ruletable.go:610: [WARN] Load binds from etcd fail.
[error]: 100: Key not found (/gateway) [5]
2016/06/30 19:57:18 ruletable.go:625: [WARN] Load aggregations from etcd fail.
[error]: 100: Key not found (/gateway) [5]
2016/06/30 19:57:18 ruletable.go:595: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/gateway) [5]
2016/06/30 19:57:18 manager.go:72: [INFO] Mgr listen at :8081.

******************************************************************
**## admin的log如下：**
start at 192.168.2.56:9090
time=2016-06-30T20:04:01-07:00, remote_ip=192.168.2.71, method=GET, uri=/, status=404, took=958.284µs, sent=9 bytes
time=2016-06-30T20:04:11-07:00, remote_ip=192.168.2.71, method=GET, uri=/gateway, status=404, took=2.547534ms, sent=9 bytes

不知道为什么admin访问的时候老是404“Not Found”。使用的用户名和密码都是：admin

**Comment by zhangxu19830126** [comment]
admin包下有个public文件夹，这个是静态资源。需要和admin的可执行文件放在同一目录下执行。

**Comment by zhangxu19830126** [comment]
先启动admin，然后在启动gateway。admin启动的时候会初始化etcd的相关目录，然后gateway会监听这些目录，动态的更新配置。

**Comment by colinwdk** [comment]
谢谢！按照您上面说的admin和gateway都可以运行了，admin能够看到网页界面了。
然后，我在Admin界面上Create Servers.创建的参数如下：
Addr:192.168.2.56:9090;
Check Path:/;
Check Timeout	:3 sec;
Check Duration:sec;
Max QPS:;
Half to Open Secs:;
Half Traffic Rate:;
To Close Count:;
那我是不是访问http://192.168.2.56:80/就相应于访问的是http://192.168.2.56:9090/这个界面呢？
ps:admin和gateway运行的时候都是默认参数，就配置了etcd的地址；192.168.2.56是程序（admin和gateway）运行的服务器；http://192.168.2.56:9090/是Admin的Dashboard的界面。
刚接触，问题比较多，麻烦了！

**Comment by zhangxu19830126** [comment]
admin的创建流程应该是这样的，1. 创建server，2.创建cluster，3. server和cluster bind起来，cluster和server是1:N，4. gateway会根据url匹配到一个cluster，5. 根据你选择的负载均衡算法算从server集合中选择一个server发送请求

**Comment by zhangxu19830126** [comment]
这个项目现在还没有经过生产系统考验。还是谢谢你做小白鼠。:-)

**Comment by zhangxu19830126** [comment]
我正在整理使用指南，过几天会放上去。

**Comment by zhangxu19830126** [comment]
举个例子：
1. 创建一个server: 192.168.2.56:8080
2. 创建一个cluster: app1，url规则是：/api/*（所有/api开头的url的请求全部转发到后面的server）
3. bind server和cluster，那么现在cluster下有一个server:192.168.2.56:8080
4.gateway的地址：192.168.2.56:80
5. 那么用户在浏览器访问：http://192.168.2.56:80/api/user?userId=xxx会被转发到192.168.2.56:8080上，
http://192.168.2.56:80/info则会报404

**Comment by colinwdk** [comment]
您好！
按照您上面说的，server还是我上面创建的，cluster也创建了：aa,url规则是：/api/*; LB:ROUNDROBIN
也绑定了。
但是我访问：http://192.168.2.56:80/api/user?userId=0  没有反应，会报503。
下面是gateway的log,您看一下：
2016/07/04 18:30:58 log.go:31: [INFO] set log level to <info>
2016/07/04 18:30:58 gateway.go:68: [INFO] conf:<&{Addr::80 MgrAddr::8081 EtcdAddr:http://127.0.0.1:2379 EtcdPrefix:/gateway LogLevel:info EnableRuntimeVal:false EnableCookieVal:false EnableHeadVal:false ReqHeadStaticMapping:map[] RspHeadStaticMapping:map[]}>
2016/07/04 18:30:58 ruletable.go:467: [INFO] RouteTable start watch.
2016/07/04 18:30:58 etcd.go:379: [INFO] Etcd watch at: </gateway>
2016/07/04 18:30:58 ruletable.go:311: [INFO] Cluster <aa> added
2016/07/04 18:30:58 analysis.go:166: [INFO] Analysis <192.168.2.56:9090,1> added
2016/07/04 18:30:58 ruletable.go:250: [INFO] Server <192.168.2.56:9090> added
2016/07/04 18:30:58 ruletable.go:345: [INFO] Bind <192.168.2.56:9090,aa> stored.
2016/07/04 18:30:58 ruletable.go:625: [WARN] Load aggregations from etcd fail.
[error]: 100: Key not found (/gateway/aggregations) [14376]
2016/07/04 18:30:58 ruletable.go:595: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/gateway/routings) [14376]
2016/07/04 18:30:58 manager.go:72: [INFO] Mgr listen at :8081.

**Comment by zhangxu19830126** [comment]
是这样的，有个细节。你创建server的时候有个check字段，这个字段是一个url，gateway会去检查这个url的返回值，必须是200返回码并且httpbody是OK字样，这样你的server才是合法的。

**Comment by colinwdk** [comment]
噢，这样啊。那您能抽空提供一个example 小web服务器程序的例子嘛？能够正确跳转过去的，成吗？

**Comment by zhangxu19830126** [comment]
再backend目录下有个backend.go，你编译下，是个可执行文件，提供http服务。支持下面2个url请求：
	e.Get("/check", check())
	e.Get("/api/call", call())
你可以使用这个试试。
还有一个，我问下，你用这个项目准备做什么事情？

**Comment by colinwdk** [comment]
好的，目前只是调研一下，做公司项目api gateway用的。之前调研过tyk，感觉有点大，也复杂。就想找个简单些的，我们也可以自己维护的那种。就找到您这了

**Comment by zhangxu19830126** [comment]
哦知道了，这个项目是我业余时间搞得，还没有在生产系统中使用过。如果你们选择基于这个项目开发，能不能直接在github上开发？我也可以一起参与？

**Comment by colinwdk** [comment]
按照上面说的修改跳转到backend，访问:80/api/call的时候还是会报503，但是gateway程序的log没有再报check fail的warn(如果在添加server的时候填写错了check path会每个几秒报check fail的，这是不是说明gateway检测到了server?)，不知道是啥原因啊，哎

**Comment by zhangxu19830126** [comment]
你的 cluster的url是正则是怎么写的？

**Comment by colinwdk** [comment]
/api/*  写的是这个

**Comment by zhangxu19830126** [comment]
能否把gateway的详细日志贴上来看看

**Comment by zhangxu19830126** [comment]
cluster和app是否bind了？

**Comment by colinwdk** [comment]
2016/07/06 01:37:00 log.go:31: [INFO] set log level to <info>
2016/07/06 01:37:00 gateway.go:68: [INFO] conf:<&{Addr:192.168.2.153:80 MgrAddr::8081 EtcdAddr:http://127.0.0.1:2379 EtcdPrefix:/gateway LogLevel:info EnableRuntimeVal:false EnableCookieVal:false EnableHeadVal:false ReqHeadStaticMapping:map[] RspHeadStaticMapping:map[]}>
2016/07/06 01:37:00 ruletable.go:467: [INFO] RouteTable start watch.
2016/07/06 01:37:00 etcd.go:379: [INFO] Etcd watch at: </gateway>
2016/07/06 01:37:00 ruletable.go:311: [INFO] Cluster <cc> added
2016/07/06 01:37:00 analysis.go:166: [INFO] Analysis <192.168.2.153:9099,1> added
2016/07/06 01:37:00 ruletable.go:250: [INFO] Server <192.168.2.153:9099> added
2016/07/06 01:37:00 ruletable.go:345: [INFO] Bind <192.168.2.153:9099,cc> stored.
2016/07/06 01:37:00 ruletable.go:625: [WARN] Load aggregations from etcd fail.
[error]: 100: Key not found (/gateway/aggregations) [22892]
2016/07/06 01:37:00 ruletable.go:595: [WARN] Load routings from etcd fail.
[error]: 100: Key not found (/gateway/routings) [22892]
2016/07/06 01:37:00 manager.go:72: [INFO] Mgr listen at :8081.
2016/07/06 01:37:02 ruletable.go:652: [INFO] Server <192.168.2.153:9099> UP.
2016/07/06 01:37:02 cluster.go:126: [INFO] Bind <192.168.2.153:9099,cc> created.
您好，这是启动的时候 gateway的log。
“cluster和app是否bind了？”  app是啥？我只把cluster和server  bind了

**Comment by zhangxu19830126** [comment]
我打错了，就是server。不是启动的日志，是后续的日志，你访问不是报503么？我想看到完整日志。

**Comment by colinwdk** [comment]
好的，太感谢了。1151714332

**Comment by ruandao** [comment]
这样聊会比较累，但是，可以给后来的人迅速查看下。。。
