### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by leeQAQ** [fagongzi/gateway#21]
请问routings板块该怎么去定义路由？这个的作用是什么？

**Comment by zhangxu19830126** [comment]
路由这块的实现不是很好，主要表现在对外设置不友好，想自定义一个DSL来做，一直没有时间去搞。
这个模块的作用主要是根据一个请求中的cookie、header、querystring中某些字段的数据，来把这个请求转发到指定的cluster，这个优先级高于API的匹配规则，所以这个模块可以用来做AB测试，灰度发布等等。

**Comment by zhangxu19830126** [comment]
desc = "test";  # describle
deadline = 100; # unit is second
# rule can use header,cookie,query runtime val, use "_" connect attr.
# can used comparison Operators are: ==,>=,<=,~(matches),in 
rule = ["$header_abc == 10", "$query_123==20", "$cookie_abc==abc", "$query_abc~^abc"]; 
or = ["$query_abc == 10", "$query_123 == 20"];  # optional

这个是一个配置例子，但是真实配置的时候需要把“#的注释部分全部删除”，不然会报错，所以我说这个实现的不友好。。。

**Comment by zhangxu19830126** [comment]
desc = "test";  # describle
deadline = 100; # unit is second
\# rule can use header,cookie,query runtime val, use "_" connect attr.
\# can used comparison Operators are: ==,>=,<=,~(matches),in 
rule = ["$header_abc == 10", "$query_123==20", "$cookie_abc==abc", "$query_abc~^abc"]; 
or = ["$query_abc == 10", "$query_123 == 20"];  # optional

**Comment by zhangxu19830126** [comment]
MD格式问题，大概这个意思

**Comment by zhangxu19830126** [comment]
可以加我微信:1367515314，方便以后交流
