### ISSUE TITLE
mac go install command-line-arguments: build output "proxy" already exists and is a directory

### ISSUE THREAD

**Issue by zzzkk2009** [fagongzi/gateway#23]
在mac下按照文档clone下来代码后，进入项目根目录下，运行go build cmd/proxy/proxy.go 报如下错误：
go install command-line-arguments: build output "proxy" already exists and is a directory

请问下这个问题怎么解决呢？

我的go sdk环境配置如下：
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="~/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jz/yzzkw_gs5z701z5_x47403gw0000gn/T/go-build946663768=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

gateway存放目录：
~/go/src/github.com/fagongzi/gateway

**Comment by zzzkk2009** [comment]
你好，我现在修改了下gopath，如下：
GOARCH="amd64"
GOBIN="~/gobin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="~/go_lib:~/go"

gateway源码存放在~/go/src目录下，运行go build cmd/proxy/proxy.go会报如下错误了：

cmd/proxy/proxy.go:12:2: cannot find package "github.com/fagongzi/gateway/pkg/conf" in any of:
	~/go/src/gateway/vendor/github.com/fagongzi/gateway/pkg/conf (vendor tree)
	/usr/local/go/src/github.com/fagongzi/gateway/pkg/conf (from $GOROOT)
	~/go_lib/src/github.com/fagongzi/gateway/pkg/conf (from $GOPATH)
	~/go/src/github.com/fagongzi/gateway/pkg/conf
能问下，我是哪里配置错了吗？

**Comment by zhangxu19830126** [comment]
go build cmd/proxy/proxy.go 会在当前目录下生成一个`proxy`的二进制文件，但是在这个目录下有一个proxy目录，所以名字冲突了，你可以有2种选择：1. cd到cmd/proxy/下后编译，2. 使用go build -o  选项重新定义二进制文件的名称

**Comment by zhangxu19830126** [comment]
不用修改gopath

**Comment by zzzkk2009** [comment]
@zhangxu19830126  可以了，非常感谢！

另外还有一个小问题，麻烦你了。我使用webstorm开发，安装了go插件，打开gateway项目后

![image](https://cloud.githubusercontent.com/assets/3713481/26619949/514f19b8-4613-11e7-8863-29bd1f9f2b3e.png)

为什么github.com/fagongzi/gateway/pkg/conf这种包会找不到呢？我检查了，对应目录和文件是存在的。

**Comment by zhangxu19830126** [comment]
我没有用webstorm开发过go程序，我感觉太重了，我用的vscode。这个问题应该和你的插件环境有关系。

目前vscode对于golang的支持比较好，建议使用vscode

**Comment by zzzkk2009** [comment]
哦，好的，谢谢啦！
