### ISSUE TITLE
在配置多个server时，server和cluster是一对一的关系，存在api请求转发错乱的问题

### ISSUE THREAD

**Issue by yuanbaobao** [fagongzi/gateway#24]
在使用的场景中，配置4个server，4个server分别属于4个cluster，并且所有api匹配规则不存在交叉的情况。在应用的场景中，需要先访问server1的api，然后再访问其他server的api，这时经常会碰到404的请求，经排查多个server的访问日志，发现404是由于api请求转发错乱导致，server1的api请求被转发到其他server服务上。

**Comment by zhangxu19830126** [comment]
问题是这样的，实现的http client 是基于ip的，所以在同一个IP的地址上的多个后端服务，就有可能错误的使用链接。

**Comment by zhangxu19830126** [comment]
fixed
