### ISSUE TITLE
建议作者提供对于Consul的支持

### ISSUE THREAD

**Issue by xinjiayu** [fagongzi/gateway#28]
在微服务构建上，当前使用Consul的很多，如果在整个技术栈里，同时维护etcd还有Consul会增加维护成本。强烈建议大侠增加这个网关对于Consul的支持。

需求就是，可以采用Consul替代etcd。并实现Consul的服务发现注册。

谢谢！！

**Comment by rfyiamcool** [comment]
+1

**Comment by zhangxu19830126** [comment]
已经开发完毕，在测试
