### ISSUE TITLE
Api 的 url 用正则的话，如果有多个url都匹配到请求的地址，有针对这种情况处理吗？

### ISSUE THREAD

**Issue by Enan01** [fagongzi/gateway#29]
as title

**Comment by zhangxu19830126** [comment]
没有，对外认为url匹配+method唯一标识了一个API，如果有重复的，运行期间使用匹配到的第一个。

**Comment by Enan01** [comment]
@zhangxu19830126 如果匹配到的第一个不是期望的，就会有问题，而且这种情况下在后台管理里面也不好配置，针对这种情况，有什么好的解决方案吗？

**Comment by weisd** [comment]
正则是会有这个问题，要么配置的时候注意，要么更换路由不用正则




发自网易邮箱大师
在2017年06月13日 21:47，Enan01 写道：

@zhangxu19830126 如果匹配到的第一个不是期望的，就会有问题，而且这种情况下在后台管理里面也不好配置，针对这种情况，有什么好的解决方案吗？

**Comment by zhangxu19830126** [comment]
这个在API网关这个层面，我目前没有想到好的办法。如果出现了2个API都可以匹配，程序如何知道，那个API是用户期望的？这个如何界定？目前只能靠人来保证，如果API都是符合restful规范的话，我觉得情况没有那么糟糕
