### ISSUE TITLE
下载的最新版Docker镜像不能够访问

### ISSUE THREAD

**Issue by CBDlkl** [fagongzi/gateway#33]
刚刚下载最新版的镜像
`docker pull fagongzi/gateway`
运行命令`docker -d -P fagongzi/gateway`
然后我访问由8080映射出来的32788端口，都不能访问。显示拒绝链接。

宿主防火墙确认开放了的。

@zhangxu19830126

**Comment by zhangxu19830126** [comment]
已经修复，请pull最新镜像
