### ISSUE TITLE
proxy在启动运行一段时间后，代理的某个server服务崩溃又快速恢复，但是proxy不能及时恢复其服务

### ISSUE THREAD

**Issue by yuanbaobao** [fagongzi/gateway#42]
设置的Server CheckResponsedBody 为空，健康检查的时间间隔为2s。经日志追踪，server xxxxx第一次健康检查失败的日志出现时，却展示累计25次失败。server.go:233: [WARN] Server <xxxxx, /check/status, 25> check fail. 
 经分析源码pkg/model/server.go func (s *Server) check() 中 if s.CheckResponsedBody == "" { return true} 在这块逻辑中没有设置succ标识为true，而直接return。这会导致succ标识的值一直为false，进而checkFailCount++ （检查失败的次数会持续累加），s.useCheckDuration += s.useCheckDuration / 2（健康检查的时间间隔会在每次健康检查后延长当次间隔的一半）。 造成的影响就是随着proxy代理server服务的时间越久，一旦server服务异常又快速恢复，但随着健康检查间隔的延长，要等到下次健康检查时间到来，才能重新bind server。

**Comment by zhangxu19830126** [comment]
fixed
