### ISSUE TITLE
http://XX.XX.XX.XX:8080/#/routings add route info failed

### ISSUE THREAD

**Issue by xuhai-sy** [fagongzi/gateway#47]
use the reate button in the page to add route info into the gateway, the response of /api/routings is ok, but can not see any new route info in the /#/routings page. I check the code pkg/model/store_consul.go:422 and find the code "pairs, _, err := s.client.KV().List(s.apisDir, nil)", maybe "pairs, _, err := s.client.KV().List(s.routingsDir, nil)" is corrected.

**Comment by zhangxu19830126** [comment]
Yes, you are right.
