### ISSUE TITLE
modal dialog

### ISSUE THREAD

**Issue by fortomcat** [fagongzi/gateway#48]
server -> list -> bind button, 弹出对话框， 此时背景变暗， 选对话框上的cluster, 然后点"Bind"按钮， 对话框消失， 但页面背景仍然是暗的， 并且不再响应鼠标。

**Comment by fortomcat** [comment]
server.js：  $scope.bind = function() {...}  中：

 $http.post('api/binds', b).success(function (data) {
                $location.path("/servers");
                $route.reload();
});

改为: 

$http.post('api/binds', b).success(function (data) {
                setTimeout(function(){
      			$location.path("/servers");
                	$route.reload();
		},500);
   });

供参考。

**Comment by zhangxu19830126** [comment]
In the webui branch,use vue rewrite the admin ui

**Comment by zhangxu19830126** [comment]
2.0.0版本放弃支持管理WEBUI，对外开放管理API，参见：https://github.com/fagongzi/gateway/tree/master/examples
