### ISSUE TITLE
health check 时间间隔无限制增长

### ISSUE THREAD

**Issue by lujiayu** [fagongzi/gateway#51]
当底层服务挂掉后，health check时间间隔会不断增长，最终变得无限大，此时若服务恢复，也不能及时检测到。所以需要一个间隔时间的天花板值，使得某服务down掉很长时间后恢复，gateway也能快速检测到并提供服务。
期望能在分钟级检测到服务恢复，所以建议天花板值能否设置在60s？

**Comment by zhangxu19830126** [comment]
fixed
