### ISSUE TITLE
server模块添加有误不能删除与编辑

### ISSUE THREAD

**Issue by woyinzf** [fagongzi/gateway#53]
如下图：addr 填写的时候多加了 "http://",此条数据不能编辑与删除

<img width="1257" alt="shanchu" src="https://user-images.githubusercontent.com/13416056/31928427-ba343636-b85d-11e7-90dd-eeb8e5fe530b.png">

**Comment by tailnode** [comment]
调用删除的接口时拼接REST url没转义，url 拼成了 /api/servers/http://xxxx

**Comment by zhangxu19830126** [comment]
2.0.0版本已解决
