### ISSUE TITLE
文件上传怎么处理?

### ISSUE THREAD

**Issue by pkptzx** [fagongzi/gateway#54]
文件上传怎么处理?

**Comment by zhangxu19830126** [comment]
现在不支持文件上传，我觉得文件上传和下载的相关API走gateway不是太合适

**Comment by pkptzx** [comment]
那客户端就复杂了,提供两个地址才行

**Comment by zhangxu19830126** [comment]
客户端不需要配置两个地址啊，可以使用类似nginx的组件把指定的url转移到文件服务，API网关如果处理文件服务，会带来非常大的开销，全局影响比较大
