### ISSUE TITLE
the protocol of the backend api 能否自己扩展？

### ISSUE THREAD

**Issue by fanriming** [fagongzi/gateway#60]
the protocol of the backend api 能否自己扩展？例如对消息队列的支持。

**Comment by zhangxu19830126** [comment]
没有明白你的意思，backend api是指什么？支持消息队列是什么场景下需要？

**Comment by fanriming** [comment]
路径: gateway/pkg/pb/metapb/metapb.pb.go
...
// Protocol is the protocol of the backend api
type Protocol int32

const (
	HTTP        Protocol = 0
	Grpc        Protocol = 1
	Dubbo       Protocol = 2
	SpringCloud Protocol = 3
)

// Server is a backend server that provide api
type Server struct {
	ID               uint64          `protobuf:"varint,1,opt,name=id" json:"id"`
	Addr             string          `protobuf:"bytes,2,opt,name=addr" json:"addr"`
	Protocol         Protocol        `protobuf:"varint,3,opt,name=protocol,enum=metapb.Protocol" json:"protocol"`
	MaxQPS           int64           `protobuf:"varint,4,opt,name=maxQPS" json:"maxQPS"`
	HeathCheck       *HeathCheck     `protobuf:"bytes,5,opt,name=heathCheck" json:"heathCheck,omitempty"`
	CircuitBreaker   *CircuitBreaker `protobuf:"bytes,6,opt,name=circuitBreaker" json:"circuitBreaker,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}
...

从源码看目前后端支持HTTP/Grpc/Dubbo/SpringCloud 4 种 Protocol，我想了解下Protocol 能否扩展，因为我们这边后端server采用的通信机制是消息队列(点对点模式)

**Comment by zhangxu19830126** [comment]
目前只支持http, GRPC等其他方式还没有支持。这块后面会搞成协议转换的插件机制。
