### ISSUE TITLE
proxy部署时，addr参数用机器的公网ip部署报错

### ISSUE THREAD

**Issue by xuhai-sy** [fagongzi/gateway#65]
我单节点部署proxy是，在centos7上部署，机器有内网ip和公网ip，用内网ip部署正常，用公网ip部署时会报错，启动失败。

[root@iZ2ze0yas4kb5a8o6z2m46Z gateway-2.0.0]# ./proxy -addr=47.95.XX.XX:8500 
2018/03/26 15:34:57.882652 [info] filter added, filter=<&{Name:WHITELIST External:false ExternalPluginFile: ExternalCfg:}>
2018/03/26 15:34:57.882726 [info] filter added, filter=<&{Name:BLACKLIST External:false ExternalPluginFile: ExternalCfg:}>
2018/03/26 15:34:57.882732 [info] filter added, filter=<&{Name:ANALYSIS External:false ExternalPluginFile: ExternalCfg:}>
2018/03/26 15:34:57.882745 [info] filter added, filter=<&{Name:RATE-LIMITING External:false ExternalPluginFile: ExternalCfg:}>
2018/03/26 15:34:57.882750 [info] filter added, filter=<&{Name:CIRCUIT-BREAKER External:false ExternalPluginFile: ExternalCfg:}>
2018/03/26 15:34:57.882755 [info] filter added, filter=<&{Name:HTTP-ACCESS External:false ExternalPluginFile: ExternalCfg:}>
2018/03/26 15:34:57.882761 [info] filter added, filter=<&{Name:HEADER External:false ExternalPluginFile: ExternalCfg:}>
2018/03/26 15:34:57.882767 [info] filter added, filter=<&{Name:XFORWARD External:false ExternalPluginFile: ExternalCfg:}>
2018/03/26 15:34:57.882773 [info] filter added, filter=<&{Name:VALIDATION External:false ExternalPluginFile: ExternalCfg:}>
2018/03/26 15:34:57.883557 [info] start server check worker
2018/03/26 15:34:57.885411 [info] load proxies
2018/03/26 15:34:57.885524 [info] router start watch meta data 
2018/03/26 15:34:57.885554 [info] watch event at: </dev>
2018/03/26 15:34:57.885937 [info] proxy <000047.95.XX.XX:8500> added
2018/03/26 15:34:57.885951 [info] proxy <00172.17.175.XX:8500> added
2018/03/26 15:34:57.885968 [info] load clusters
2018/03/26 15:34:57.886458 [info] cluster <10> added, data <id:10 name:"c1" >
2018/03/26 15:34:57.886467 [info] load servers
2018/03/26 15:34:57.888486 [info] analysis: added, key=<1004> interval=<1s>
2018/03/26 15:34:57.888636 [info] server <1004> added, data <id:1004 addr:"60.205.XX.XX:8000" maxQPS:50 heathCheck:<path:"/ping" checkInterval:10000000000 timeout:30000000000 > >
2018/03/26 15:34:57.888653 [info] load binds
2018/03/26 15:34:57.891992 [info] server <1004> UP
2018/03/26 15:34:57.892011 [info] bind <10,1004> created
2018/03/26 15:34:57.892015 [info] bind <10,1004> actived
2018/03/26 15:34:57.892017 [info] load apis
proto: no coders for metapb.Parameter
proto: no encoder for Parameter metapb.Parameter [GetProperties]
proto: no slice oenc for *reflect.rtype = []*reflect.rtype
proto: no encoder for Rules []metapb.ValidationRule [GetProperties]
2018/03/26 15:34:57.892604 [info] api <1008> added, data <id:1008 name:"api3" urlPattern:"/pc/(.+)" method:"*" status:Up nodes:<clusterID:10 > >
2018/03/26 15:34:57.892637 [info] api <1009> added, data <id:1009 name:"api3" urlPattern:"/ping/(.+)" method:"*" status:Up nodes:<clusterID:10 > >
2018/03/26 15:34:57.892654 [info] api <1010> added, data <id:1010 name:"api3" urlPattern:"/weixin/(.+)" method:"*" nodes:<clusterID:10 > >
2018/03/26 15:34:57.892658 [info] load routings
2018/03/26 15:34:57.893561 [info] gateway proxy started at <47.95.XX.XX:8500>
2018/03/26 15:34:57.893619 [fatal] gateway proxy start failed, errors:
listen tcp4 47.95.xx.xx:8500: bind: cannot assign requested address

**Comment by zhangxu19830126** [comment]
请使用`ifconfig`查看是否有公网IP地址，你的机器的公网地址并不一定绑定在你的机器上，这个公网地址可能是浮动的或者使用类似NAT的技术，只是会把流量导入进来，所以当前机器上的程序不能够监听这个ip地址上的端口。这种情况下，一般来说监听内网地址就足够了，或者监听："0.0.0.0:port"

**Comment by xuhai-sy** [comment]
我试过监听"0.0.0.0:port"，也报相同的错误，我用的是阿里云的ECS，可能跟这个有关。目前看绑内网ip可以用，外网也可以直接访问绑定端口

**Comment by xluohome** [comment]
估计你用的是阿里云vpc ecs ，如果是那就是
上面说的情况。

发自我的 iPhone
