### ISSUE TITLE
有UI配置页面嘛？

### ISSUE THREAD

**Issue by dongjiang1989** [fagongzi/gateway#69]
有UI配置页面嘛？

**Comment by zhangxu19830126** [comment]
没有

**Comment by ArchFish** [comment]
@zhangxu19830126 可以把这个打上需求标签，说不准有贡献者可以帮忙写一个，分工合作嘛

**Comment by ArchFish** [comment]
@dongjiang1989 试一下这个 https://github.com/ArchFish/gateway_ui
