### ISSUE TITLE
filter 处理失败，以固定json 返回

### ISSUE THREAD

**Issue by silva6** [fagongzi/gateway#70]
hi @zhangxu19830126 ,

自定义filter，希望处理失败时，返回客户端还是一段固定的json，http code 为200

比如 `{"code":499, "msg":"session 校验失败"}`

不知是否可以支持？

**Comment by silva6** [comment]
这样风险较大，万一真是下游有问题，以这个为默认返回，客户端都会被踢下线。预期只在filter pre 失败时，以上面json为固定返回，其他情况不能返回这个

**Comment by silva6** [comment]
我们session校验也是一个http服务，为api加session验证是不是可以用`依赖聚合`这种方式？

**Comment by zhangxu19830126** [comment]
目前不支持在filter pre失败的时候，使用filter自己指定的返回结果结束后续流程。以后考虑加入这个特性
