### ISSUE TITLE
希望加强apis对http code的支持

### ISSUE THREAD

**Issue by wilehos** [fagongzi/gateway#79]
比如我们有一个活动的h5页面，如果服务器不可用了，就直接给用户暴露出了{"code":200,"data":"","msg":"服务异常，请重新尝试"}，如果能跳转到指定的页面，会更友好。

**Comment by zhangxu19830126** [comment]
defaultvalue 增加code字段。可以设置返回的状态吗。重定向的header需要自己设置在defaultvalue的header中
