### ISSUE TITLE
能写点例子吗？

### ISSUE THREAD

**Issue by xwinie** [fagongzi/gateway#8]
能写点例子吗？能更好让其他人员上手！

**Comment by zhangxu19830126** [comment]
原来demo网站上有例子，没人删除了，我尽快恢复！

**Comment by weisd** [comment]
看来是又被删除了，例子的后台登陆进去数据没有 @zhangxu19830126

**Comment by zhangxu19830126** [comment]
这个是对外公开的，大家随便操作，我实在没有办法控制，你看看doccn里面的文档应该可以了。自己再尝试搭建一下。
