### ISSUE TITLE
请教下util下task，没有看到任何调用RunJob的地方

### ISSUE THREAD

**Issue by aiadaniel** [fagongzi/gateway#80]
也就是没有任何地方调用newJob，有点看不懂这个task的运行机制

**Comment by archfish** [comment]
@aiadaniel 问题是属于 https://github.com/fagongzi/util 项目的，这里提问不太合适。

ps：项目里我看了一下只使用了 Runner的RunCancelableTask方法。

pps：vendor中的内容都是引用的其它项目的，这个目录下的疑问到相应项目下提问比较好。
