### ISSUE TITLE
Error when install on mac

### ISSUE THREAD

**Issue by skanger** [fagongzi/gateway#87]
I tried with 'git clone' , 'go get', 'download zip', but none worked

env: 
golang 1.9
macOS 10.13.2

error with 'git clone' and same as 'go get': 
`git clone https://github.com/fagongzi/gateway.git
Cloning into 'gateway'...
remote: Counting objects: 13134, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 13134 (delta 0), reused 1 (delta 0), pack-reused 13128
Receiving objects: 100% (13134/13134), 32.29 MiB | 79.00 KiB/s, done.
Resolving deltas: 100% (4722/4722), done.
error: unable to create symlink vendor/github.com/coreos/etcd/Documentation/README.md: File name too long
error: unable to create symlink vendor/github.com/coreos/etcd/cmd/etcd: File name too long
error: unable to create symlink vendor/github.com/coreos/etcd/cmd/etcdctl: File name too long
error: unable to create symlink vendor/github.com/coreos/etcd/cmd/tools: File name too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'`

error with 'unzip'
![image](https://user-images.githubusercontent.com/18080860/42855488-51fe537e-8a73-11e8-8c1a-9f6b084f1a3a.png)

how can i solved this? (CSDN博客上说zip解压失败可能是子文件夹的问题，是不是vendor文件夹依赖呆导致的？感谢你的开源与帮助)

**Comment by zhangxu19830126** [comment]
你需要打开git的long.path，主要问题是"file name too long"

**Comment by skanger** [comment]
我觉得是系统的设置并没有生效，这个错误应该是OS层返回的错误

**Comment by skanger** [comment]
File name too long 是不是因为vendor层文件夹太深造成的呢

**Comment by zhangxu19830126** [comment]
你是什么操作系统

**Comment by zhangxu19830126** [comment]
应该是的，vendors里面的etcd的cmd里面，有几个软链接，导致的。这个是dep包管理工具搞进来的，我来把这些去掉

**Comment by skanger** [comment]
![image](https://user-images.githubusercontent.com/18080860/42863054-65ecb116-8a94-11e8-8959-9be959419902.png)
Etcd的文档似乎也需要处理

**Comment by zhangxu19830126** [comment]
坑爹的mac。
