### ISSUE TITLE
rate-limit filter 多个proxy下的限流问题

### ISSUE THREAD

**Issue by iodone** [fagongzi/gateway#9]
负载均衡加多个proxy，rate-limiter的qps计算是不是会有问题？
计算qps好像是有状态的，proxy不是完全stateless的吧

**Comment by zhangxu19830126** [comment]
这个问题是这样的，每个proxy的qps计算只是针对当前单个proxy的节点。部署多个Proxy的情况下：举个例子一个Server能够保证1000的qps，我们部署10个proxy，那么Server的qps设置可以设置为100，最终10个proxy最大的情况下的qps为：10*100=1000.

**Comment by zhangxu19830126** [comment]
另外，在Proxy扩容和缩容的时候，可能需要重新调整Server的qps值，这些调整是实时生效的。

**Comment by iodone** [comment]
Ok，了解
rate-limit 目前还不支持api（URL）入口层面的流量限制，后续考虑支持么？针对api的调用情况统计？
filter能否支持自定义，方便扩展一些定制化需求？

**Comment by zhangxu19830126** [comment]
我不太清楚针对API入口的流量限制的目的是什么？是指API的调用次数限制？还是单纯的qps的限制？如果是调用次数限制，这个倒是可以考虑，如果是qps的限制，那么我觉得这样做的意义不是很大

**Comment by zhangxu19830126** [comment]
关于扩展的问题，我考虑是等1.8发布了，利用plugin机制来做，后续有计划的

**Comment by iodone** [comment]
API的流量限制是考虑如果支持auth，可以控制每个使用该api的用户的调用频次。

**Comment by zhangxu19830126** [comment]
这个在我规划范围里面的。

**Comment by iodone** [comment]
有roadmap么？方便发布出来不？

**Comment by zhangxu19830126** [comment]
我整理下思路，过几天放上来

**Comment by carl-leopard** [comment]
你好， 最近也是在做微服务网关， 我们数据加密使用rsa， 导致性能过低。 经过测试， go rsa 加解密的官方库的性能也不高， 有什么方法解决吗？
