### ISSUE TITLE
什么鬼，运行了根目录下的Makefile，自动删除了我好多文件夹，包括了根目录的文件

### ISSUE THREAD

**Issue by esolo0121** [fagongzi/gateway#93]
如题，用户下的所有文件夹都空了。
![image](https://user-images.githubusercontent.com/8187529/43789775-70260898-9aa3-11e8-8cd1-33134945b766.png)

**Comment by zhangxu19830126** [comment]
你的执行命令是什么?

**Comment by zhangxu19830126** [comment]
是不是在gateway目录下执行的

**Comment by archfish** [comment]
@esolo0121 麻烦提供一下你的shell操作及输出日志。mac下通过以下命令执行是没有问题的：

- 项目根目录下`make clean`
- 任意位置 `make --makefile Projects/gateway/Makefile clean`

根据你的图片，我猜你可能执行了 `/bin/sh Makefile` - -|||
这个不是Makefile的执行方式。。。
